# -------
# Purpose
# -------
# Reshape data output files generated by Zhenggang via Matlab. These files have 
# numeric data in the form of scientific notation, but as count data they should 
# be integers. Additionally, these data need to be reformatted such that each 
# observation is its own row. 

# ----------------------
# Variables
# ----------------------
# animal_id : 1...6
# bout_num : 1...n
# time_bin : "1s","2s","3s"...20s
# laser : "on", "off"

# --------------
# Load libraries 
# --------------
library(tidyr)
library(dplyr)
library(ggplot2)
library(boot) # boot
library(rstudioapi) 

# ---------
# R version
# ---------
# 4.2.2

# ---------------------
# Set working directory
# ---------------------
# Dynamically set working directory to source of script
original_wd = setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# -----------------------
# Set up batch processing
# -----------------------
# List subdirectories
subdirs = list.dirs(".", full.names=TRUE, recursive=FALSE)

# Iterate through each subdirectory
for (subdir in subdirs) {
  # Print current subdirectory
  print(paste("Processing:", subdir))
  # Set current subdirectory as current working directory
  
  setwd(subdir)
  
  # ---------
  # Read data
  # ---------
  dat_off = data.table::fread("ANMid_lickF_OFF.txt", header=FALSE)
  dat_on = data.table::fread("ANMid_lickF_ON.txt", header=FALSE)
  
  # ----------------------------
  # Convert all data to integers
  # ----------------------------
  # Zhenggang's raw output files generated by Matlab have data values in scientific notation
  dat_off = dat_off %>%
    mutate(across(where(is.numeric), as.integer))
  dat_on = dat_on %>%
    mutate(across(where(is.numeric), as.integer))
  
  # -------------------
  # Assign column names
  # -------------------
  time_bin_names = paste(1:20, "s", sep = "")
  colnames(dat_off) = c("animal_id", time_bin_names)
  colnames(dat_on) = c("animal_id", time_bin_names)
  
  
  # Populate new column "bout_num"
  dat_off  = dat_off %>%
    group_by(animal_id) %>% 
    mutate(bout_num = row_number()) %>% 
    ungroup() %>%
    relocate(bout_num, .after = animal_id) 
  
  dat_on  = dat_on %>%
    group_by(animal_id) %>%
    mutate(bout_num = row_number()) %>% 
    ungroup() %>%
    relocate(bout_num, .after = animal_id) 
  
  
  # ------------
  # Reshape data
  # ------------
  
  # Reshape OFF data from wide to long format
  long_dat_off <- dat_off %>%
    pivot_longer(
      cols = ends_with("s"),  
      names_to = "time_bin",
      values_to = "licks"
    ) %>%
    mutate(
      time_bin = as.numeric(gsub("s", "", time_bin)), # Extract numeric time bin values
      laser = "off" # Populate a new column "laser"
    )
  
  # Reshape ON data from wide to long format
  long_dat_on <- dat_on %>%
    pivot_longer(
      cols = ends_with("s"),  
      names_to = "time_bin",
      values_to = "licks"
    ) %>%
    mutate(
      time_bin = as.numeric(gsub("s", "", time_bin)),  # Extract numeric time bin values
      laser = "on" # Populate a new column "laser"
    )
  
  # -----------------------
  # Combine OFF and ON data
  # -----------------------
  combined_long_dat = rbind(long_dat_off, long_dat_on)
  
  # ------------------
  # Save reshaped data
  # ------------------
  # output_file_name = paste(basename(subdir),"_reshaped_data.txt")
  write.table(combined_long_dat, "reshaped_data.txt", row.names = FALSE, sep = "\t")
  
  # ----------------------------
  # Return to original directory
  # ----------------------------
  setwd(original_wd)
  
} # end of for loop